#!/bin/bash

# seetup bridge name
BRIDGE="natbr0"

if [ -n "$1" ]; then
	echo "Tearing down network bridge for $1" > /var/log/qemu/nat.log
	ifconfig $1 down
	brctl delif "$BRIDGE" $1

	nrtap=$(brctl show $BRIDGE | grep $BRIDGE | awk '{ print NF }')
	[ $nrtap -eq 3 ] && ifconfig $BRIDGE down && brctl delbr $BRIDGE && pkill dnsmasq

	#iptables -t nat -F
	#iptables -t filter -F
	exit 0
else
	echo "Error: no interface specified"  > /var/log/qemu/nat.log
	exit 1
fi
